spring:
  application:
    name: movie-search-service
  
  profiles:
    active: local
  
  rabbitmq:
    host: localhost
    port: 5672
    username: feature_flags_user
    password: feature_flags_password
    connection-timeout: 2000ms
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        prefetch: 1
        default-requeue-rejected: false

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.moviesearch: DEBUG
    org.springframework.amqp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8081
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# OMDB API Configuration
omdb:
  api:
    base-url: http://www.omdbapi.com
    key: ${OMDB_API_KEY:demo_key}
    timeout: 5000ms

---
spring:
  config:
    activate:
      on-profile: docker
  
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:feature_flags_user}
    password: ${SPRING_RABBITMQ_PASSWORD:feature_flags_password}

---
spring:
  config:
    activate:
      on-profile: dev
  
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:feature_flags_user}
    password: ${SPRING_RABBITMQ_PASSWORD:feature_flags_password}

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true

logging:
  level:
    com.moviesearch: DEBUG
    org.springframework: INFO

---
spring:
  config:
    activate:
      on-profile: test
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
